In [2]:
import numpy as np 

In [11]:
random_vector=np.random.randint(1,21,15)
print(random_vector)
reshaped_vector=np.reshape(random_vector,(3,5))
print(reshaped_vector)
print(reshaped_vector.shape)

[20  6 14 10 20 20 18  1 16  6 12 10 12  6 18]
[[20  6 14 10 20]
 [20 18  1 16  6]
 [12 10 12  6 18]]
(3, 5)


In [12]:
Maximum_elements=np.amax(reshapingvector,axis=1)
print(Maximum_elements)
Maximum_elements=Maximum_elements[:,None]
print(Maximum_elements)
Array=np.where(reshapingvector==Maximum_elements,0,reshapingvector)
print(Array)

[16 16 17]
[[16]
 [16]
 [17]]
[[ 5 13  5  0  7]
 [ 8  0 11  3  6]
 [ 5  0 16  9 16]]
